config/routes.rb
Rails.application.routes.draw do
  #this shows the index html page for blog posts
  root 'blog_posts#index'

  # generates all CRUD urls for blog posts
  resources :blog_posts

  # # this shows the show html page for a specific blog post
  # get 'blog_posts/:id', to: 'blog_posts#show'
  #
  # # responsible for showing the user the new HTML form
  # get 'blog_posts/new', to: 'blog_posts#new'
  #
  # # responsible for creating a new blog post record in our database
  # post 'blog_posts', to: 'blog_posts#create'
  #
  # # responsible for showing the user an edit form
  # get 'blog_posts/edit/:id', to: 'blog_posts#edit'
  #
  # # responsible for updating a record in our database
  # put 'blog_posts/edit/:id', to: 'blog_posts#update'
  #
  # # responsible for deleting a blog post record
  # delete 'blog_posts/:id', to: 'blog_posts#delete'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  # GET
  # listing all blog posts
  def index
    @blog_posts = BlogPost.all
  end

  # GET
  # showing a single blog post
  def show
    @blog_post = BlogPost.find(params[:id])
  end

  # GET
  # showing the user a form to fill out for a new blog post
  def new
    @blog_post = BlogPost.new
  end

  # POST
  # responsible for creating a new blog post record
  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      # got a new record in the database
      redirect_to blog_post_path(@blog_post)
    else
      # something went wrong, have user fix errors on the form
      render :new
    end
  end

  # GET
  # showing the user a form to edit a existing blog post
  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  # PUT / PATCH
  # finding the record to update and updating it
  def update
    @blog_post = BlogPost.find(params[:id])
    if @blog_post.update(blog_post_params)
      redirect_to blog_post_path(@blog_post)
    else
      render :edit
    end
  end

  # DELETE
  # finds a record and removes it from the table
  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy
    redirect_to blog_post_path
  end

  # Strong Params
  private
    def blog_post_params
      params.require(:blog_post).permit(:title, :author, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/edit.html.erb
<h1> Edit Post </h1>
<hr />

<%= form_for @blog_post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />

  <%= f.label :author %>
  <%= f.text_field :author %>
  <br />

  <%= f.label :body %>
  <%= f.text_field :body %>
  <br />

  <%= f.submit %>
<% end %>

app/views/blog_posts/index.html.erb
<h1>All Blog Posts</h1>
<hr />

<%= link_to 'Create New Post', new_blog_post_path %>

<% if @blog_posts.empty? %>
  <h3>No Blog Posts Found, Please Create One!</h3>
<% else %>
  <ul>
    <% @blog_posts.each do |blog_post| %>
      <li>
        <%= link_to blog_post.title, blog_post_path(blog_post) %>
        <span> - </span>
        <%= link_to 'Edit', edit_blog_post_path(blog_post) %>
        <span> - </span>
        <%= link_to 'Delete', blog_post_path(blog_post), method: :delete %>
      </li>
    <% end %>
  </ul>
<% end %>

<!--Non-Echoing ERB Tag
loops
conditionals
var setting
<% %>

Echoing ERB Tag
variable values
<%= %>-->

app/views/blog_posts/new.html.erb
<h1>Create New Blog Post<h1>
<hr />

<%= form_for @blog_post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />

  <%= f.label :author %>
  <%= f.text_field :author %>
  <br />

  <%= f.label :body %>
  <%= f.text_field :body %>
  <br />

  <%= f.submit %>
<% end %>

app/views/blog_posts/show.html.erb
<h1>
  <%= @blog_post.title %>
</h1>

<blockquote>
  <%= @blog_post.body %>
</blockquote>

<i>
  <%= @blog_post.author %>
</i>

<i>
  Posted At: <%= @blog_post.created_at %>
</i>

<br />
<%= link_to 'All Posts', blog_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>